In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('spotify-2023.csv')

In [3]:
df.head()

track_name    artist(s)_name  artist_count  \
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook             2   
1                                 LALA       Myke Towers             1   
2                              vampire    Olivia Rodrigo             1   
3                         Cruel Summer      Taylor Swift             1   
4                       WHERE SHE GOES         Bad Bunny             1   

   released_year  released_month  released_day  in_spotify_playlists  \
0           2023               7            14                   553   
1           2023               3            23                  1474   
2           2023               6            30                  1397   
3           2019               8            23                  7858   
4           2023               5            18                  3133   

   in_spotify_charts    streams  in_apple_playlists  ...  bpm key   mode  \
0                147  141381703                  43  ...  125   B  Major   
1                 48  133716286                  48  ...   92  C#  Major   
2                113  140003974                  94  ...  138   F  Major   
3                100  800840817                 116  ...  170   A  Major   
4                 50  303236322                  84  ...  144   A  Minor   

  danceability_%  valence_% energy_% acousticness_%  instrumentalness_%  \
0             80         89       83             31                   0   
1             71         61       74              7                   0   
2             51         32       53             17                   0   
3             55         58       72             11                   0   
4             65         23       80             14                  63   

   liveness_%  speechiness_%  
0           8              4  
1          10              4  
2          31              6  
3          11             15  
4          11              6  

[5 rows x 24 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    int64 
 3   released_year         953 non-null    int64 
 4   released_month        953 non-null    int64 
 5   released_day          953 non-null    int64 
 6   in_spotify_playlists  953 non-null    int64 
 7   in_spotify_charts     953 non-null    int64 
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    int64 
 10  in_apple_charts       953 non-null    int64 
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    int64 
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    int64 
 15  key                   858 non-null    ob

In [5]:
df.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [6]:
df['artist(s)_name'][0]

'Latto, Jung Kook'

In [7]:
df['artist(s)_name'][1]

'Myke Towers'

In [8]:
df.head(1)['artist(s)_name'].values

array(['Latto, Jung Kook'], dtype=object)

In [9]:
df.shape

(953, 24)

In [10]:
df = df[['track_name','artist(s)_name','released_year']]

In [11]:
df.head()

track_name    artist(s)_name  released_year
0  Seven (feat. Latto) (Explicit Ver.)  Latto, Jung Kook           2023
1                                 LALA       Myke Towers           2023
2                              vampire    Olivia Rodrigo           2023
3                         Cruel Summer      Taylor Swift           2019
4                       WHERE SHE GOES         Bad Bunny           2023

In [12]:
df.isnull().sum()

track_name        0
artist(s)_name    0
released_year     0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(4)

In [14]:
duplicates = df[df.duplicated()]
print(duplicates)

           track_name artist(s)_name  released_year
482  SPIT IN MY FACE!       ThxSoMch           2022
616    Take My Breath     The Weeknd           2021
764   About Damn Time          Lizzo           2022
873              SNAP      Rosa Linn           2022


In [15]:
df['artist(s)_name'].value_counts()

artist(s)_name
Taylor Swift                   34
The Weeknd                     22
Bad Bunny                      19
SZA                            19
Harry Styles                   17
                               ..
Ludwig Goransson, Foudeqush     1
Jin                             1
Selena Gomez                    1
Feid, Paulo Londra              1
Shae Gill, Ali Sethi            1
Name: count, Length: 645, dtype: int64

In [16]:
df['artist(s)_name'][0]

'Latto, Jung Kook'

In [18]:
df['artist(s)_name'][102]

'Post Malone'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [21]:
vectors = cv.fit_transform(df['artist(s)_name']).toarray()

In [22]:
cv.fit_transform(df['artist(s)_name']).toarray().shape

(953, 1022)

In [23]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(953, 1022))

In [24]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(1022,))

In [25]:
cv.get_feature_names_out()

array(['070', '20', '21', ..., '½sto', '½u', '½ï'],
      shape=(1022,), dtype=object)

In [26]:
len(cv.get_feature_names_out())

1022

In [27]:
import nltk

In [28]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [29]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
        

In [31]:
df['artist(s)_name'] = df['artist(s)_name'].apply(stem)

In [32]:
df['artist(s)_name'][1]

'myke tower'

In [33]:
df['artist(s)_name'][3]

'taylor swift'

In [34]:
stem('taylor swift')

'taylor swift'

In [35]:
from sklearn.metrics.pairwise import cosine_similarity

In [36]:
cosine_similarity(vectors).shape

(953, 953)

In [37]:
similarity = cosine_similarity(vectors)

In [38]:
similarity[0]

array([1.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.51639778, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [39]:
similarity[1]

array([0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.63245553, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [40]:
sorted(list(enumerate(similarity[0])),reverse =True,key=lambda x:x[1])[1:6]

[(94, np.float64(0.816496580927726)),
 (650, np.float64(0.816496580927726)),
 (62, np.float64(0.5163977794943223)),
 (396, np.float64(0.5163977794943223)),
 (1, np.float64(0.0))]

In [51]:
def recommend(song_name):
    song_index = df[df['track_name'] == song_name].index[0]
    distances = similarity[song_index]
    song_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    for i in song_list:
        print(df.iloc[i[0]].track_name)


In [52]:
recommend('Apna Bana Le (From "Bhediya")')

Phir Aur Kya Chahiye (From "Zara Hatke Zara Bachke")
Kesariya (From "Brahmastra")
Tere Vaaste (From "Zara Hatke Zara Bachke")
Jhoome Jo Pathaan
Seven (feat. Latto) (Explicit Ver.)


In [54]:
recommend('Before You Go')

Before You Go
Forget Me
How Do I Say Goodbye
Can't Hold Us (feat. Ray Dalton)
Seven (feat. Latto) (Explicit Ver.)


In [55]:
recommend('Flowers')

Angels Like You
Seven (feat. Latto) (Explicit Ver.)
LALA
vampire
Cruel Summer


In [56]:
recommend('Angels Like You')

Angels Like You
Seven (feat. Latto) (Explicit Ver.)
LALA
vampire
Cruel Summer


In [57]:
recommend('vampire')

good 4 u
drivers license
deja vu
happier
favorite crime
